### ISSUE TITLE
[Figma]: Адаптировать макет под структуру сайта

### ISSUE THREAD

**Issue by Ruslick** [Ruslick/potato-chat-app#28]

**Comment by Ruslick** [comment]
Создать пейджи:

1. enter-username (page)
2. reset-password (page)
3. modal

**Comment by Foxitocin** [comment]
В [этой](https://www.figma.com/file/Cg95MzY7rcvsJzDhySOLb9/Potato-chat?type=design&node-id=3-3&mode=design&t=Za5oYLySB3JcH1jW-4) секции адаптировала все пэйджи согласно тому, как сделано в ветке develop

1. [Enter username](https://www.figma.com/file/Cg95MzY7rcvsJzDhySOLb9/Potato-chat?type=design&node-id=75-47&mode=design&t=Za5oYLySB3JcH1jW-4)
2. [Reset password](https://www.figma.com/file/Cg95MzY7rcvsJzDhySOLb9/Potato-chat?type=design&node-id=75-57&mode=design&t=Za5oYLySB3JcH1jW-4)
3. На эти страницы в макете добавлена кнопка закрытия (modal)
