### ISSUE TITLE
Figma: страница "подтверждение email"

### ISSUE THREAD

**Issue by Ruslick** [Ruslick/potato-chat-app#5]

**Comment by Ruslick** [comment]
Сделать в фигме страницу, подтверждение email, с кодом который должен придти на email

**Comment by Foxitocin** [comment]
Готово  [здесь]( https://www.figma.com/file/Cg95MzY7rcvsJzDhySOLb9/Potato-chat?type=design&node-id=28-18&mode=design&t=9YxWxO5U4DZpt8Rn-4)
Нужны правки?
